# This is a basic workflow that is manually triggered
deploymentid: 4795765486390
name: Build Website And App
WEBSITEANDAPPID: 7436589070983698743589670349768
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Make OS'
        # Default value if no value is explicitly provided
        default: 'OPERATING SYSTEM No. 89749853705987'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: build, deploy website, pages and app deployment, deploy to google play store, publish
  # This workflow contains a single job called "greet"
  greet: apps and pages build deployment
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
